### ISSUE TITLE
Question regarding one-shot results

### ISSUE THREAD

**Issue by MSiam** [lzzcd001/OSLSM#12]
Hello

I wanted to inquire about the results reported in Table 1 in the paper. The mean IoU reported there is on the new classes only or does it include as well the background class? Based on the paper explanation the labels you are evaluating with are binary masks per new class in the query image. So the mean IoU includes both the background class and the new class from the current fold. Is this correct?

**Comment by haamoon** [comment]
Hi MSiam,

I am not 100% sure if I understand the question. Here I describe the way we are doing it. Please feel free to ask any follow up questions.

We pick a query image which has pixels from one of the new classes. Lets say "cow" is the new class in Image "Q". Given the target class "cow" we also sample a support set. The binary label for image Q and any image in the support set is simply +1 for every pixel that belongs to the class "cow" and 0 otherwise. As you mentioned, pixels with label 0 might be from background class (grass, trees, and etc.)  or 19 other classes in PASCAL VOC (old or new) but conditioned on the supportset images and their labels the target class is "cow" (with label +1) and anything else if considered as non-target (with label 0). We compute the IoU by comparing the network binary prediction and the label of Q.

Best,
Amirreza

**Comment by MSiam** [comment]
Thank you so much that answers my question.

**Comment by MSiam** [comment]
Hello,

   I wanted to confirm something when computing the mean IoU, now we have two classes foreground and background. So you are reporting the meanIoU on both classes background and foreground correct?
Thanks
